CREATE DATABASE RH
GO

USE RH
GO

CREATE TABLE CARGO(
    IDCARGO INT IDENTITY PRIMARY KEY,
    NOME_CARGO VARCHAR(30) NOT NULL,
    SALARIO_MIN MONEY NOT NULL,
    SALARIO_MAX MONEY NOT NULL
)
GO

CREATE TABLE EMPREGADO(
    IDEMPREGADO INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ID_CARGO INT,
    SALARIO_ATUAL MONEY NOT NULL
)
GO

CREATE TABLE HIST_SALARIO(
    IDHISTORICO INT IDENTITY PRIMARY KEY,
    ID_EMPREGADO INT,
    SALARIO_ANTIGO MONEY,
    SALARIO_NOVO MONEY,
    DATA_ALTERACAO DATETIME DEFAULT GETDATE()
)
GO

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_CARGO
FOREIGN KEY (ID_CARGO) REFERENCES CARGO (IDCARGO)
GO

ALTER TABLE HIST_SALARIO ADD CONSTRAINT FK_HIST_SALARIO_EMPREGADO
FOREIGN KEY (ID_EMPREGADO) REFERENCES EMPREGADO (IDEMPREGADO)
GO
