CREATE TRIGGER HISTORICO_SALARIO
ON dbo.EMPREGADO
FOR UPDATE AS IF UPDATE(SALARIO_ATUAL)
BEGIN
    INSERT INTO HIST_SALARIO
    (ID_EMPREGADO,SALARIO_ANTIGO,SALARIO_NOVO,DATA_ALTERACAO)
    SELECT D.IDEMPREGADO, D.SALARIO_ATUAL, I.SALARIO_ATUAL, GETDATE()
    FROM DELETED D, INSERTED I 
    WHERE D.IDEMPREGADO = I.IDEMPREGADO 
END
GO
