CREATE TRIGGER FAIXA_SALARIO
ON dbo.EMPREGADO
FOR INSERT, UPDATE
AS
    DECLARE
        @MINSAL MONEY,
        @MAXSAL MONEY,
        @ATUALSAL MONEY,
        @IDCARGO INT

    SELECT  @IDCARGO = I.ID_CARGO,
            @ATUALSAL = I.SALARIO_ATUAL 
    FROM INSERTED I 

    SELECT  @MINSAL = SALARIO_MIN, 
            @MAXSAL = SALARIO_MAX
    FROM CARGO
    WHERE IDCARGO = @IDCARGO 

    IF(@ATUALSAL < @MINSAL)
    BEGIN
            RAISERROR('SALARIO MENOR QUE O PISO', 16, 1)
            ROLLBACK TRANSACTION
            RETURN
    END

    IF(@ATUALSAL > @MAXSAL)
    BEGIN
            RAISERROR('SALARIO MAIOR QUE O TETO', 16, 1)
            ROLLBACK TRANSACTION
            RETURN
    END
GO