/*ATUALIZAR SALARIO DE UM FUNCIONARIO*/
UPDATE EMPREGADO SET SALARIO_ATUAL = SALARIO_ATUAL * 1.5
WHERE IDEMPREGADO = 4
GO

/*ATUALIZAR SALARIO DE TODOS OS FUNCIONARIOS DE UM CARGO*/
UPDATE EMPREGADO SET SALARIO_ATUAL = SALARIO_ATUAL * 1.1
WHERE ID_CARGO = 2
GO 

/*MEDIA SALARIAL POR CARGO*/
SELECT C.NOME_CARGO, AVG(E.SALARIO_ATUAL) AS MEDIA_SALARIAL
FROM EMPREGADO E 
INNER JOIN CARGO C ON E.ID_CARGO = C.IDCARGO
GROUP BY C.NOME_CARGO
GO 

/*TOTAL DE FUNCIONARIOS POR CARGO*/
SELECT  C.NOME_CARGO, COUNT(E.IDEMPREGADO) AS TOTAL_FUNCIONARIOS
FROM EMPREGADO E 
INNER JOIN CARGO C ON E.ID_CARGO = C.IDCARGO
GROUP BY C.NOME_CARGO
GO 

/*CONSULTAR HISTORICO DE UM FUNCIONARIO*/
SELECT  H.DATA_ALTERACAO, 
        H.SALARIO_ANTIGO, 
        H.SALARIO_NOVO
FROM HIST_SALARIO H 
INNER JOIN EMPREGADO E ON H.ID_EMPREGADO = E.IDEMPREGADO 
WHERE E.NOME = 'JOAO SILVA'
ORDER BY H.DATA_ALTERACAO DESC
GO 

/*FUNCIONARIO COM SALARIO ACIMA DE UM VALOR*/
SELECT NOME, SALARIO_ATUAL AS SALARIO
FROM EMPREGADO
WHERE SALARIO_ATUAL > 4000;
GO 

/*REMOVER FUNCIONARIO*/
DELETE FROM EMPREGADO 
WHERE NOME = 'PEDRO OLIVEIRA'
GO 

/*CONSULTAR FUNCIONARIOS E SEUS CARGOS*/
SELECT  E.NOME, 
        C.NOME_CARGO AS CARGO, 
        E.SALARIO_ATUAL AS SALARIO
FROM EMPREGADO E
INNER JOIN CARGO C ON E.ID_CARGO = C.IDCARGO
ORDER BY C.NOME_CARGO, E.SALARIO_ATUAL DESC
GO

/*FUNCIONARIOS QUE TIVERAM AUMENTO NOS ULTIMOS 7 DIAS*/
SELECT E.NOME, H.SALARIO_ANTIGO, H.SALARIO_NOVO, H.DATA_ALTERACAO
FROM HIST_SALARIO H
INNER JOIN EMPREGADO E ON H.ID_EMPREGADO = E.IDEMPREGADO
WHERE H.DATA_ALTERACAO >= DATEADD(DAY, -7, GETDATE())
GO

/*HISTORICO DE REAJUSTES RECENTES*/
SELECT  H.IDHISTORICO,
        E.NOME AS NOME_FUNCIONARIO,
        H.SALARIO_ANTIGO,
        H.SALARIO_NOVO,
        (H.SALARIO_NOVO - H.SALARIO_ANTIGO) AS DIFERENCA,
        H.DATA_ALTERACAO
FROM HIST_SALARIO H
INNER JOIN EMPREGADO E ON H.ID_EMPREGADO = E.IDEMPREGADO
ORDER BY H.DATA_ALTERACAO DESC
GO 